module.exports = {
    MORTGAGE_CALC: 'mortgageCalc',

    MORTGAGE_CALC_INITIAL_LOAN: 'initialLoan ',
    MORTGAGE_CALC_DOWN_PAYMENT: 'downPayment',

    CURRENT_YEAR: new Date().getFullYear(),
    USER_ID_LENGTH: 24,
    MORTGAGE_CALC_DOWN_PAYMENT_MIN: 1,
    MORTGAGE_CALC_DOWN_PAYMENT_MAX: 120000,

    MORTGAGE_CALC_INITIAL_LOAN_MIN: 1,
    MORTGAGE_CALC_INITIAL_LOAN_MAX: 120000,
};
